// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3QTJXLcJrlzBvFvkNnf96qnUo7e_Huk',
    appId: '1:556909001986:web:dd56c06414c3824f36561b',
    messagingSenderId: '556909001986',
    projectId: 'watsapp-be267',
    authDomain: 'watsapp-be267.firebaseapp.com',
    storageBucket: 'watsapp-be267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nhVgiKodn5--cBhCVB2UTeHZI3kfskY',
    appId: '1:556909001986:android:9e11e27e3ca4df9836561b',
    messagingSenderId: '556909001986',
    projectId: 'watsapp-be267',
    storageBucket: 'watsapp-be267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAloA2qjK5stwVgvTnBhKVxyOsQXxrxPfg',
    appId: '1:556909001986:ios:14629cc9f0a539d636561b',
    messagingSenderId: '556909001986',
    projectId: 'watsapp-be267',
    storageBucket: 'watsapp-be267.appspot.com',
    iosBundleId: 'com.example.ecommers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAloA2qjK5stwVgvTnBhKVxyOsQXxrxPfg',
    appId: '1:556909001986:ios:b085158388308d1c36561b',
    messagingSenderId: '556909001986',
    projectId: 'watsapp-be267',
    storageBucket: 'watsapp-be267.appspot.com',
    iosBundleId: 'com.example.ecommers.RunnerTests',
  );
}
